# Applied Machine Learning

### Question 5
#### Implement a Logistic Regression model in Machine Learningand fit the model to predict heart rate of a person based on age and BMI. Use “framingham.csv” dataset.

In [1]:
#importing all libraries.
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
from sklearn.metrics import classification_report
from sklearn.preprocessing import Binarizer

%matplotlib inline

In [2]:
data = pd.read_csv("framingham.csv")
data.head()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0

In [3]:
#data = data[["age", "BMI", "heartRate"]] #Dropped unwanted features
#data.head()

In [4]:
data.isnull().sum() #checking missing valus

male                 0
age                  0
education          105
currentSmoker        0
cigsPerDay          29
BPMeds              53
prevalentStroke      0
prevalentHyp         0
diabetes             0
totChol             50
sysBP                0
diaBP                0
BMI                 19
heartRate            1
glucose            388
TenYearCHD           0
dtype: int64

In [5]:
data = data.dropna() #found 19 missing values in BMI and 1 in Heartrate. 
#It can create problems in accurate prediction. Hence dropping rows with missing values

In [6]:
data.isnull().sum() #checking whether all missing values are dropped or no

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [7]:
data

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,80.0,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,95.0,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,75.0,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,65.0,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,85.0,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4233,1,50,1.0,1,1.0,0.0,0,1,0,313.0,179.0,92.0,25.97,66.0,86.0,1
4234,1,51,3.0,1,43.0,0.0,0,0,0,207.0,126.5,80.0,19.71,65.0,68.0,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,80.0,107.0,0
4238,1,40,3.0,0,0.0,0.0,0,1,0,185.0,141.0,98.0,25.60,67.0,72.0,0
4239,0,39,3.0,1,30.0,0.0,0,0,0,196.0,133.0,86.0,20.91,85.0,80.0,0

In [8]:
data.describe()

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
count,3658.000000,3658.000000,3658.000000,3658.000000,3658.000000,3658.000000,3658.000000,3658.000000,3658.000000,3658.000000,3658.000000,3658.000000,3658.000000,3658.000000,3658.000000,3658.000000
mean,0.443685,49.551941,1.980317,0.489065,9.025424,0.030344,0.005741,0.311646,0.027064,236.847731,132.370558,82.917031,25.782802,75.730727,81.852925,0.152269
std,0.496886,8.562029,1.022656,0.499949,11.921590,0.171557,0.075561,0.463229,0.162292,44.097681,22.086866,11.974258,4.065601,11.981525,23.904164,0.359331
min,0.000000,32.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,113.000000,83.500000,48.000000,15.540000,44.000000,40.000000,0.000000
25%,0.000000,42.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,206.000000,117.000000,75.000000,23.080000,68.000000,71.000000,0.000000
50%,0.000000,49.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,234.000000,128.000000,82.000000,25.380000,75.000000,78.000000,0.000000
75%,1.000000,56.000000,3.000000,1.000000,20.000000,0.000000,0.000000,1.000000,0.000000,263.000000,143.875000,90.000000,28.037500,82.000000,87.000000,0.000000
max,1.000000,70.000000,4.000000,1.000000,70.000000,1.000000,1.000000,1.000000,1.000000,600.000000,295.000000,142.500000,56.800000,143.000000,394.000000,1.000000

In [9]:
# According to domain research, heart rate should be in between 60 and 100
# i) 0 if heart rate is lesser than 60 or greater than 100
# ii) 1 if heart rate is in between 60 and 100
#tempRate = data.heartRate.values
#print(tempRate)

In [10]:
#heartRateBinary = [0]*len(tempRate)

In [11]:
#for i in range(0, len(tempRate)):
#    if tempRate[i]<60:
 #       heartRateBinary[i]=0
  #  elif tempRate[i]>100:
   #     heartRateBinary[i]=0
    #else:
     #   heartRateBinary[i]=1

In [12]:
data['heartRate'] = data['heartRate'].astype('category')

In [13]:
data['heartRate'] = pd.cut(data.heartRate, [44, 75, 143], labels = ["High Risk", "Low Risk"])

In [14]:
data

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,Low Risk,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,Low Risk,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,High Risk,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,High Risk,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,Low Risk,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4233,1,50,1.0,1,1.0,0.0,0,1,0,313.0,179.0,92.0,25.97,High Risk,86.0,1
4234,1,51,3.0,1,43.0,0.0,0,0,0,207.0,126.5,80.0,19.71,High Risk,68.0,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,Low Risk,107.0,0
4238,1,40,3.0,0,0.0,0.0,0,1,0,185.0,141.0,98.0,25.60,High Risk,72.0,0
4239,0,39,3.0,1,30.0,0.0,0,0,0,196.0,133.0,86.0,20.91,Low Risk,80.0,0

In [15]:
data.isnull().sum() #checking whether all missing values are dropped or no

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          1
glucose            0
TenYearCHD         0
dtype: int64

In [16]:
data.dropna(inplace=True)

In [17]:
data.isnull().sum() #checking whether all missing values are dropped or no

male               0
age                0
education          0
currentSmoker      0
cigsPerDay         0
BPMeds             0
prevalentStroke    0
prevalentHyp       0
diabetes           0
totChol            0
sysBP              0
diaBP              0
BMI                0
heartRate          0
glucose            0
TenYearCHD         0
dtype: int64

In [18]:
data

,male,age,education,currentSmoker,cigsPerDay,BPMeds,prevalentStroke,prevalentHyp,diabetes,totChol,sysBP,diaBP,BMI,heartRate,glucose,TenYearCHD
0,1,39,4.0,0,0.0,0.0,0,0,0,195.0,106.0,70.0,26.97,Low Risk,77.0,0
1,0,46,2.0,0,0.0,0.0,0,0,0,250.0,121.0,81.0,28.73,Low Risk,76.0,0
2,1,48,1.0,1,20.0,0.0,0,0,0,245.0,127.5,80.0,25.34,High Risk,70.0,0
3,0,61,3.0,1,30.0,0.0,0,1,0,225.0,150.0,95.0,28.58,High Risk,103.0,1
4,0,46,3.0,1,23.0,0.0,0,0,0,285.0,130.0,84.0,23.10,Low Risk,85.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4233,1,50,1.0,1,1.0,0.0,0,1,0,313.0,179.0,92.0,25.97,High Risk,86.0,1
4234,1,51,3.0,1,43.0,0.0,0,0,0,207.0,126.5,80.0,19.71,High Risk,68.0,0
4237,0,52,2.0,0,0.0,0.0,0,0,0,269.0,133.5,83.0,21.47,Low Risk,107.0,0
4238,1,40,3.0,0,0.0,0.0,0,1,0,185.0,141.0,98.0,25.60,High Risk,72.0,0
4239,0,39,3.0,1,30.0,0.0,0,0,0,196.0,133.0,86.0,20.91,Low Risk,80.0,0

In [19]:
# independent variable
in_var = ['age', 'BMI']
X=data[in_var]
# dependent variable
y=data.heartRate

In [20]:
X

      age    BMI
0      39  26.97
1      46  28.73
2      48  25.34
3      61  28.58
4      46  23.10
...   ...    ...
4233   50  25.97
4234   51  19.71
4237   52  21.47
4238   40  25.60
4239   39  20.91

[3657 rows x 2 columns]

In [21]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler().fit(X)

In [22]:
X = scaler.transform(X)

In [23]:
X

array([[-1.23231468,  0.2919708 ],
       [-0.41461532,  0.72487246],
       [-0.18098694, -0.10895518],
       ...,
       [ 0.28626984, -1.06084691],
       [-1.11550049, -0.0450038 ],
       [-1.23231468, -1.19858835]])

In [24]:
y.value_counts()

High Risk    2144
Low Risk     1513
Name: heartRate, dtype: int64

In [25]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=7) 
#splitted dataset into train and test

In [26]:
X_train.shape #no. of rows and columns in training data in X-axis

(2742, 2)

In [27]:
X_test.shape #no. of rows and columns in testing data in X-axis

(915, 2)

In [28]:
y_train.value_counts()

High Risk    1594
Low Risk     1148
Name: heartRate, dtype: int64

In [29]:
y_test.value_counts()

High Risk    550
Low Risk     365
Name: heartRate, dtype: int64

In [30]:
lr = LogisticRegression() #instantiated logistic regression model

In [31]:
#fitting model with training data
lr.fit(X_train,y_train)

LogisticRegression()

In [32]:
y_pred=lr.predict(X_test)

In [33]:
y_pred #predicted values

array(['High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'Low Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'Low Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'Low Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'Low Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'Low Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'Low Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'Low Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'Low Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'Low Risk',
       'High Risk', 'Low Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'Low Risk', 'High Risk',
       'Low Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'Low Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'Low Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk',
       'High Risk', 'High Risk', 'High Risk', 'High Risk', 'High Risk'],
      dtype=object)

In [34]:
y_test #actual values

1117     Low Risk
1102     Low Risk
3682    High Risk
1541    High Risk
978      Low Risk
          ...
527     High Risk
387     High Risk
29      High Risk
1313     Low Risk
617      Low Risk
Name: heartRate, Length: 915, dtype: category
Categories (2, object): ['High Risk' < 'Low Risk']

In [35]:
con_mat = metrics.confusion_matrix(y_test, y_pred)  #confusion matrix
print(con_mat)

[[544   6]
 [357   8]]

In [36]:
print('Accuracy: ',metrics.accuracy_score(y_test, y_pred)*100,'%')

Accuracy:  60.32786885245902 %

In [37]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

   High Risk       0.60      0.99      0.75       550
    Low Risk       0.57      0.02      0.04       365

    accuracy                           0.60       915
   macro avg       0.59      0.51      0.40       915
weighted avg       0.59      0.60      0.47       915